### PR TITLE
random_select_set function implementation.

### PR DESCRIPTION
**Pull request by batucs**
- implementation of the random_select_set function.

### CODE REVIEW

**Comment by batucs** [comment]
# The following code is a test environment to emulate the random set retrieval for random_select_set under class/DesignHandler.
## Libraries: random

```python
import random



L = [
        [
            ('name', '', 'Pikachu'),
        ],
        [
            ('set', 'name', 'Hidden Legends'),
            ('set', 'name', 'FireRed & LeafGreen'),
            ('set', 'name', 'Unseen Forces'),
            ('set', 'name', 'EX Trainer Kit Latios'),
        ],
        [
            ('set', 'name', 'XY'),
            ('set', 'name', 'Hidden Fates'),
            ('types', '', 'Grass'),
            ('types', '', 'Fire'),
            ('types', '', 'Water'),
            ('types', '', 'Electric'),
            ('types', '', 'Psychic'),
            ('types', '', 'Dark'),
            ('types', '', 'Dragon'),
            ('types', '', 'Steel'),
            ('types', '', 'Fairy'),
            ('types', '', 'Fighting'),
            ('types', '', 'Colorless'),
        ]
    ]

T = [
    
]

def main():

    # writing like this to avoid larger cluster of for loops
    T = [element for sublist in L for element in sublist if element[0] == 'set']
    if T:
        print(random.choice(T))
        return random.choice(T)
    if not T:
        print("No set found")
        return None

if __name__ == "__main__":
    main()

```

**Comment by TelloViz** [comment]
@batucs 

I had an idea to make this more generic to be able to handle ANY category (set, types, etc). It would eliminate the need for 2 separate nearly identical functions.

Hold on for now I will try do describe what I mean. I will also test this version you made asap to check out how it works.

**Comment by TelloViz** [comment]
And what I meant by making a test file, is a file that actually tests your function, not just the code IN your function. So it would import the discoverhandler module, then it would use the class like our program would DiscoverHandler.random_select_set()... 

Also, I'm pretty sure your algorithm is filtering out tuples by set, BUT it's combining all of the searches into one list of tuples. So it's essentially combining all the 'set' tuples form each list into one list with all of the set tuples.

**Review by TelloViz — APPROVED** [review]
I updated this file:

- Moved python library imports to first imports in file
- Made random_select_set more generic
   - Now selects 1 tuple of each category
   - Now returns `list[tuple[str, str, str]]` for simpler use and to account for more randomly selected tuples.

**Pull request merged**
